### ISSUE TITLE
ProcessExecutionDetector not working on PIE ELF?

### ISSUE THREAD

**Issue by Owlz** [S2E/libs2eplugins#10]
Playing around with the plugins, I've created a simple test binary with the following c:

```c
#include <stdio.h>
#include <string.h>

int main() {
    char buf[32];

    fgets(buf, 32, stdin);

    if (strstr(buf, "winner") == buf) {
        printf("Win!");
    }

    return 0;
}
```

I have been writing a plugin to take in a list of addresses to avoid at runtime, instead of having to compile them separately. This works for non-PIE binaries, however the following call seems to fail on PIE ELF binaries:

Pseudo-code:
```c
m_procDetector = s2e()->getPlugin<ProcessExecutionDetector>();
m_procDetector->isTracked(state)
```

Here's what I gather for what is and isn't working:

- ELF
  - Non-PIE (working)
  - PIE
     - 64-bit (not working)
     - 32-bit (working)
- PE (unknown)
- Mach-o (unknown)

When it fails, it seems to just never return true, even though the binary appears to run.

**Comment by adrianherrera** [comment]
Hmm something that may be causing this is currently in the `LinuxMonitor` plugin (which feeds info to `ProcessDetector`) is that we hardcode the `task_struct` offset that points to the PID (see http://elixir.free-electrons.com/linux/latest/source/include/linux/sched.h#L483). The value currently hard-coded is for i386, and so there is a high chance that this offset is different for x64.

I'm currently refactoring the code so that this is no longer hardcoded because IMO there are too many variables (the offset depends on the kernel version, the architecture, etc.).

When I'm done it would be super-cool if you could test it for me and see if it fixes your issue!

**Comment by adrianherrera** [comment]
Hey @Owlz,

If you get the chance could you please retry both the 32 and 64-bit kernels with the branch at https://github.com/S2E/libs2eplugins/pull/11 and let me know how it goes. Thanks!

~Adrian

**Comment by adrianherrera** [comment]
Hey again,

So I've done a lot of digging on this. In short, none of the PID tracking code in `LinuxMonitor` (i.e. when you call `getPid`) actually works 😃

The reason is because in `LinuxMonitor` we get the current PID via the TSS and `thread_info` pointer, essentially as described [here](https://stackoverflow.com/questions/11961490/understanding-the-getting-of-task-struct-pointer-from-process-kernel-stack) (where `current_stack_pointer` is stored in ESP0 of the task register).

However, it turns out this method (and the `thread_info` struct in general) was deprecated and removed from versions 4.x of the kernel. Now the only real way of getting the current `task_struct` is directly via the exported `current_task` pointer.

This will require some rearchitecting, so bare with me while I look into it a bit more.

~Adrian
